server:
  http2:
    enabled: true
  ssl:
    key-store-type: PKCS12
    key-store: classpath:localhostP12Keystore.p12
    key-store-password: buggateway
    certificate-private-key: classpath:localhost.key
    enabled: true

logging:
  level:
    root: info